### ISSUE TITLE
Quickblox iOS SDK Error: No Application Found

### ISSUE THREAD

**Issue by djErock** [djErock/Telemed#1]
I am trying to create a basic QBRequest and login a user or at least get an error back that the User doesn't exist. I am getting this error in the console. 

NSErrorFailingURLKey=https://api.quickblox.com/session.json, 
NSLocalizedRecoverySuggestion=
{"errors":{"base":["No application found"]}},
com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 4e6f2061 70706c69 63617469 6f6e2066 6f756e64 225d7d7d>, 
NSLocalizedDescription=Request failed: client error (422)

I have checked the syntax and gone through all the steps to correctly include the SDK. It continues to say: "No application found". I checked my credentials and everything is entered correctly in the appDelegate.

I am also receiving an error while trying to set up the Endpoints customization: Xcode keeps telling me that: QBConnectionZoneTypeProduction ia a use of unresolved identifier..

Thank you.

**Comment by soulfly** [comment]
Please show how you setup SDK -  how you setup appid, key & secret - all this init code.

**Comment by djErock** [comment]
> View Ticket: #44523

Entire code base minus credentials is here: https://github.com/djErock/Telemed


Erik Grosskurth
Software Engineer/Interactive Specialist
egrosskurth@caduceususa.com
Hapeville Clinic
678.525.7434
www.caduceususa.com
The information in this email (and any attachments) is confidential and may be covered under the Privacy Act, 5 USC 552(a), and/or the Health Insurance Portability and Accountability Act (PL 104-191). Healthcare and personal information is sensitive and must be protected accordingly. You, the recipient, are obligated to maintain it in a safe, secure and confidential manner. If you are not the intended recipient, you must not read, use or disseminate the information. If you have received this e-mail in error, please immediately click notify via ‘REPLY’ command and permanently delete the original and any copies or printouts.

**Comment by djErock** [comment]
// Set settings for zone
QBSettings.setApiEndpoint("https://enetrepriseapi.quickblox.com", chatEndpoint: "chatenterprise.quickblox.com", forServiceZone: **.production)**
// Activate zone
QBSettings.setServiceZone(**.production**)

Editing this code block fixed the issue for connecting the SDK in the enterprise environment.
